<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet ekr_test ?>
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="amd.20150913232631.1"><vh>@settings</vh>
<v t="amd.20150913232631.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="amd.20150913232631.3"><vh>@string initial_split_orientation = horizontal</vh></v>
<v t="amd.20150915153206.1"><vh>專案說明</vh>
<v t="amd.20150919102209.1" a="E"><vh>使用工具</vh>
<v t="amd.20150919112415.1"><vh>影片檔案</vh></v>
</v>
<v t="amd.20150919102541.1"><vh>pelican 與 Markdown</vh></v>
</v>
</v>
<v t="amd.20150919102739.1"><vh>專案架構</vh>
<v t="amd.20150919113520.1"><vh>@edit .gitignore</vh></v>
<v t="amd.20150919103428.1"><vh>reveal.js 設定</vh></v>
<v t="amd.20150919103341.1"><vh>Jupyter 設定</vh>
<v t="amd.20150919103923.1"><vh>設定檔案位置</vh></v>
<v t="amd.20150919104249.1"><vh>檢查 profile 位置</vh></v>
</v>
<v t="amd.20150919103357.1"><vh>pelican 設定</vh></v>
<v t="amd.20150920030003.1"><vh>IPython notebook 整合</vh></v>
<v t="amd.20150919112710.1"><vh>@path pelican</vh>
<v t="amd.20150919113340.1"><vh>以下為與 pelican 有關的設定檔案</vh></v>
<v t="amd.20150919113132.1"><vh>@edit publishconf.py</vh></v>
</v>
</v>
<v t="amd.20150919113957.1"><vh>以下為 pelican 文章</vh></v>
<v t="amd.20150919124128.1"><vh>@button pelican content</vh></v>
<v t="amd.20150919114010.1" a="E"><vh>@path pelican\content</vh>
<v t="amd.20150919114035.1"><vh>@edit 2015cphww1.md</vh></v>
<v t="amd.20150920000911.1"><vh>@edit 2015cpnote1.md</vh></v>
<v t="leo.20151116214200.1"><vh>@path 40423203</vh>
<v t="leo.20151116214200.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151116214200.3"><vh>@edit 40423203_cp_w1_p.html</vh></v>
<v t="leo.20151116214200.4"><vh>@edit 40423203_cp_w2_p.html</vh></v>
<v t="leo.20151116214200.5"><vh>@edit 40423203_cp_w3_p.html</vh></v>
<v t="leo.20151116214200.6"><vh>@edit 40423203_cp_w4_p.html</vh></v>
<v t="leo.20151116214200.7"><vh>@edit 40423203_cp_w5_p.html</vh></v>
<v t="leo.20151116214200.8"><vh>@edit 40423203_cp_w6_p.html</vh></v>
<v t="leo.20151116214200.9"><vh>@edit 40423203_cp_w7_p.html</vh></v>
<v t="leo.20151116214200.10"><vh>@edit 40423203_cp_w8_p.html</vh></v>
<v t="leo.20151116214200.11"><vh>@edit 40423203_cp_w9_p.html</vh></v>
<v t="leo.20151116214200.12"><vh>@path pelican</vh>
<v t="leo.20151116214200.13"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151116214200.14"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151116214200.15"><vh>@path content</vh>
<v t="leo.20151116214200.16"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151116214200.17"><vh>@edit 40423203_cp_w1.md</vh></v>
<v t="leo.20151116214200.18"><vh>@edit 40423203_cp_w2.md</vh></v>
<v t="leo.20151116214200.19"><vh>@edit 40423203_cp_w3.md</vh></v>
<v t="leo.20151116214200.20"><vh>@edit 40423203_cp_w4.md</vh></v>
<v t="leo.20151116214200.21"><vh>@edit 40423203_cp_w5.md</vh></v>
<v t="leo.20151116214200.22"><vh>@edit 40423203_cp_w6.md</vh></v>
<v t="leo.20151116214200.23"><vh>@edit 40423203_cp_w7.md</vh></v>
<v t="leo.20151116214200.24"><vh>@edit 40423203_cp_w8.md</vh></v>
<v t="leo.20151116214200.25"><vh>@edit 40423203_cp_w9.md</vh></v>
</v>
</v>
</v>
</v>
<v t="amd.20150919120205.1"><vh>以下為 reveal 投影片</vh></v>
<v t="amd.20150913233943.1"><vh>@clean cadpbw1.html</vh>
<v t="amd.20150913233943.2" a="E"><vh>html</vh>
<v t="amd.20150913233943.3" a="E"><vh>head</vh>
<v t="amd.20150913233943.4"><vh>title</vh></v>
</v>
<v t="amd.20150913233943.5" a="E"><vh>body</vh>
<v t="amd.20150913233943.6" a="E"><vh>div</vh>
<v t="amd.20150913233943.7" a="E"><vh>div</vh>
<v t="amd.20150913234947.1"><vh>title page</vh>
<v t="amd.20150913235225.1"><vh>標題頁下的子頁</vh></v>
</v>
<v t="amd.20150913235034.1"><vh>本日要點</vh></v>
<v t="amd.20150914000138.1"><vh>Anaconda Python</vh></v>
<v t="amd.20150914000332.1" a="E"><vh>設計的表達方式</vh>
<v t="amd.20150914000332.2"><vh>協同模式下的網際雲端內容呈現</vh></v>
</v>
<v t="amd.20150913235123.1"><vh>結論</vh></v>
</v>
</v>
<v t="amd.20150913233943.81"><vh>script</vh></v>
<v t="amd.20150913233943.82"><vh>script</vh></v>
<v t="amd.20150913233943.83"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915155634.1"><vh>@clean cadpaw1.html</vh>
<v t="amd.20150915155634.2" a="E"><vh>html 標註</vh>
<v t="amd.20150915155634.3" a="E"><vh>head</vh>
<v t="amd.20150915155634.4"><vh>title - 標題</vh></v>
<v t="amd.20150915155634.5"><vh>meta - 說明</vh></v>
<v t="amd.20150915155634.7"><vh>script - css 與 pdf 列印</vh></v>
</v>
<v t="amd.20150915155634.8"><vh>body</vh>
<v t="amd.20150915155634.9" a="E"><vh>div - reveal</vh>
<v t="amd.20150915155634.10" a="E"><vh>div - slides</vh>
<v t="amd.20150915155634.11"><vh>h1 - 課程說明</vh></v>
<v t="amd.20150915172241.1"><vh>h1 - 開放自評規劃</vh></v>
<v t="amd.20150915155634.12"><vh>h2 - 實體輔助工具</vh></v>
<v t="amd.20150915155634.13"><vh>h2 - 垂直有下屬頁</vh>
<v t="amd.20150915155634.14"><vh>h2</vh></v>
<v t="amd.20150915155634.15"><vh>h2</vh></v>
<v t="amd.20150915155634.16"><vh>h2</vh></v>
</v>
<v t="amd.20150915173703.1"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915173703.2" a="E"><vh>pre</vh>
<v t="amd.20150915173703.3"><vh>code</vh></v>
</v>
<v t="amd.20150915173703.4"><vh>p</vh></v>
</v>
<v t="amd.20150915155634.17"><vh>h2</vh></v>
<v t="amd.20150915204710.1"><vh>內嵌 Vimeo 影片</vh></v>
<v t="amd.20150915155634.18"><vh>h2</vh></v>
<v t="amd.20150915155634.19"><vh>h2</vh></v>
<v t="amd.20150915155634.20"><vh>markdown 頁面</vh></v>
<v t="amd.20150915155634.21" a="E"><vh>h2</vh>
<v t="amd.20150915160450.1"><vh>Fragement 主頁面</vh></v>
<v t="amd.20150915155634.28" a="E"><vh>下屬頁面</vh>
<v t="amd.20150915161424.1"><vh>h2</vh></v>
<v t="amd.20150915155634.29"><vh>p</vh></v>
<v t="amd.20150915155634.30"><vh>p</vh></v>
<v t="amd.20150915155634.31"><vh>p</vh></v>
<v t="amd.20150915155634.32"><vh>p</vh></v>
<v t="amd.20150915155634.33"><vh>p</vh></v>
<v t="amd.20150915155634.34"><vh>p</vh></v>
<v t="amd.20150915155634.35"><vh>p</vh></v>
</v>
</v>
<v t="amd.20150915155634.36"><vh>h2</vh></v>
<v t="amd.20150915155634.37"><vh>p</vh>
<v t="amd.20150915155634.38"><vh>a</vh></v>
<v t="amd.20150915155634.39"><vh>a</vh></v>
<v t="amd.20150915155634.40"><vh>a</vh></v>
<v t="amd.20150915155634.41"><vh>a</vh></v>
<v t="amd.20150915155634.42"><vh>a</vh></v>
<v t="amd.20150915155634.43"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.44"><vh>h2 - 更換主題</vh></v>
<v t="amd.20150915155634.45" a="E"><vh>p</vh>
<v t="amd.20150915155634.46"><vh>a</vh></v>
<v t="amd.20150915155634.47"><vh>a</vh></v>
<v t="amd.20150915155634.48"><vh>a</vh></v>
<v t="amd.20150915155634.49"><vh>a</vh></v>
<v t="amd.20150915155634.50"><vh>a</vh></v>
<v t="amd.20150915155634.51"><vh>a</vh></v>
<v t="amd.20150915155634.52"><vh>a</vh></v>
<v t="amd.20150915155634.53"><vh>a</vh></v>
<v t="amd.20150915155634.54"><vh>a</vh></v>
<v t="amd.20150915155634.55"><vh>a</vh></v>
<v t="amd.20150915155634.56"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.57"><vh>h2</vh></v>
<v t="amd.20150915155634.58"><vh>p</vh>
<v t="amd.20150915155634.59"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.60"><vh>a</vh></v>
<v t="amd.20150915155634.61"><vh>h2</vh></v>
<v t="amd.20150915155634.62" a="E"><vh>pre</vh>
<v t="amd.20150915155634.63"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.64"><vh>h2 - 背景填圖頁面</vh></v>
<v t="amd.20150915155634.65" a="E"><vh>pre</vh>
<v t="amd.20150915155634.66"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.67" a="E"><vh>div</vh>
<v t="amd.20150915155634.68"><vh>h2</vh></v>
<v t="amd.20150915155634.69"><vh>pre</vh>
<v t="amd.20150915155634.70"><vh>code</vh></v>
</v>
</v>
<v t="amd.20150915155634.71"><vh>h2</vh></v>
<v t="amd.20150915155634.72"><vh>h2</vh></v>
<v t="amd.20150915155634.73"><vh>p</vh></v>
<v t="amd.20150915155634.74"><vh>pre</vh>
<v t="amd.20150915155634.75"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.76"><vh>h2 - 背景轉換</vh></v>
<v t="amd.20150915155634.77"><vh>p</vh></v>
<v t="amd.20150915155634.78" a="E"><vh>pre</vh>
<v t="amd.20150915155634.79"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.80" a="E"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915155634.81" a="E"><vh>pre</vh>
<v t="amd.20150915155634.82"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.83"><vh>p</vh></v>
</v>
<v t="amd.20150915155634.85"><vh>h2</vh></v>
<v t="amd.20150915155634.86" a="E"><vh>ul</vh>
<v t="amd.20150915155634.87"><vh>li</vh></v>
<v t="amd.20150915155634.88"><vh>li</vh></v>
<v t="amd.20150915155634.89"><vh>li</vh></v>
<v t="amd.20150915155634.90"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.91"><vh>h2</vh></v>
<v t="amd.20150915155634.92"><vh>ol</vh>
<v t="amd.20150915155634.93"><vh>li</vh></v>
<v t="amd.20150915155634.94"><vh>li</vh></v>
<v t="amd.20150915155634.95"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.96"><vh>h2 - 表格頁面</vh></v>
<v t="amd.20150915155634.97" a="E"><vh>table</vh>
<v t="amd.20150915155634.98"><vh>thead</vh>
<v t="amd.20150915155634.99"><vh>tr</vh>
<v t="amd.20150915155634.100"><vh>th</vh></v>
<v t="amd.20150915155634.101"><vh>th</vh></v>
<v t="amd.20150915155634.102"><vh>th</vh></v>
</v>
</v>
<v t="amd.20150915155634.103"><vh>tbody</vh>
<v t="amd.20150915155634.104"><vh>tr</vh>
<v t="amd.20150915155634.105"><vh>td</vh></v>
<v t="amd.20150915155634.106"><vh>td</vh></v>
<v t="amd.20150915155634.107"><vh>td</vh></v>
</v>
<v t="amd.20150915155634.108"><vh>tr</vh>
<v t="amd.20150915155634.109"><vh>td</vh></v>
<v t="amd.20150915155634.110"><vh>td</vh></v>
<v t="amd.20150915155634.111"><vh>td</vh></v>
</v>
<v t="amd.20150915155634.112"><vh>tr</vh>
<v t="amd.20150915155634.113"><vh>td</vh></v>
<v t="amd.20150915155634.114"><vh>td</vh></v>
<v t="amd.20150915155634.115"><vh>td</vh></v>
</v>
</v>
</v>
<v t="amd.20150915155634.116"><vh>h2</vh></v>
<v t="amd.20150915155634.117"><vh>p</vh>
<v t="amd.20150915155634.118"><vh>q</vh></v>
</v>
<v t="amd.20150915155634.119"><vh>blockquote</vh></v>
<v t="amd.20150915155634.120"><vh>h2</vh></v>
<v t="amd.20150915155634.121"><vh>p</vh>
<v t="amd.20150915155634.122"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.123"><vh>h2</vh></v>
<v t="amd.20150915155634.124" a="E"><vh>p</vh>
<v t="amd.20150915155634.125"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.126"><vh>p</vh>
<v t="amd.20150915155634.127"><vh>em</vh></v>
</v>
<v t="amd.20150915155634.128"><vh>h2</vh></v>
<v t="amd.20150915155634.129"><vh>p</vh>
<v t="amd.20150915155634.130"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.131"><vh>iframe</vh></v>
<v t="amd.20150915155634.132"><vh>h2</vh></v>
<v t="amd.20150915155634.133" a="E"><vh>p</vh>
<v t="amd.20150915155634.134"><vh>code</vh></v>
<v t="amd.20150915155634.135"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.136"><vh>h2</vh></v>
<v t="amd.20150915155634.137"><vh>p</vh>
<v t="amd.20150915155634.138"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.139"><vh>pre</vh>
<v t="amd.20150915155634.140"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.141"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="amd.20150915155634.142"><vh>p</vh></v>
<v t="amd.20150915155634.143" a="E"><vh>h2 unordered list 頁面</vh>
<v t="amd.20150915155634.148"><vh>li</vh>
<v t="amd.20150915155634.149"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.150"><vh>li</vh>
<v t="amd.20150915155634.151"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.152"><vh>li</vh>
<v t="amd.20150915155634.153"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.146"><vh>li</vh>
<v t="amd.20150915155634.147"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.145"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.154"><vh>結束單頁</vh></v>
</v>
</v>
<v t="amd.20150915155634.158"><vh>script</vh></v>
<v t="amd.20150915155634.159"><vh>script</vh></v>
<v t="amd.20150915155634.160"><vh>script</vh></v>
</v>
</v>
</v>
<v t="ibm.20150918175403.1"><vh>@clean cpw1.html</vh>
<v t="ibm.20150918175403.2"><vh>檔案說明</vh></v>
<v t="ibm.20150918175403.3" a="E"><vh>html 標註</vh>
<v t="ibm.20150918175403.4" a="E"><vh>body 標註</vh>
<v t="ibm.20150918175403.5" a="E"><vh>div class="reveal"</vh>
<v t="ibm.20150918175403.6" a="E"><vh>div class="slides"</vh>
<v t="ibm.20150918175403.7"><vh>有關我的作業</vh></v>
<v t="ibm.20150918175403.8"><vh>課程規劃</vh></v>
<v t="ibm.20150918175403.9"><vh>作業規劃</vh></v>
<v t="ibm.20150918175711.1"><vh>Git 操作</vh></v>
<v t="ibm.20150918175951.1"><vh>Jupyter 操作</vh></v>
<v t="ibm.20150918181528.1"><vh>結論</vh></v>
</v>
</v>
<v t="ibm.20150918175403.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915211341.1"><vh>@clean simplest.html</vh>
<v t="amd.20150917085040.1"><vh>檔案說明</vh></v>
<v t="amd.20150915211351.1" a="E"><vh>html 標註</vh>
<v t="amd.20150915211351.4" a="E"><vh>body 標註</vh>
<v t="amd.20150915211351.5" a="E"><vh>div class="reveal"</vh>
<v t="amd.20150915211351.6" a="E"><vh>div class="slides"</vh>
<v t="amd.20150915211351.7"><vh>有關我的作業</vh></v>
<v t="amd.20150915211351.9"><vh>作業任務一</vh></v>
<v t="amd.20150915211351.12"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="amd.20150915211351.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915170743.1"><vh>@clean v31ref.html</vh>
<v t="amd.20150915170743.2" a="E"><vh>html 標註</vh>
<v t="amd.20150915170743.3" a="E"><vh>head</vh>
<v t="amd.20150915170743.4"><vh>title - 標題</vh></v>
<v t="amd.20150915170743.5"><vh>meta - 說明</vh></v>
<v t="amd.20150915170743.6"><vh>script - css 與 pdf 列印</vh></v>
</v>
<v t="amd.20150915170743.7" a="E"><vh>body</vh>
<v t="amd.20150915170743.8" a="E"><vh>div - reveal</vh>
<v t="amd.20150915170743.9" a="E"><vh>div - slides</vh>
<v t="amd.20150915170743.10"><vh>h1 - 一般單頁</vh></v>
<v t="amd.20150915170743.11"><vh>h2</vh></v>
<v t="amd.20150915170743.12" a="E"><vh>h2 - 垂直有下屬頁</vh>
<v t="amd.20150915170743.13"><vh>h2</vh></v>
<v t="amd.20150915170743.14"><vh>h2</vh></v>
<v t="amd.20150915170743.15"><vh>h2</vh></v>
</v>
<v t="amd.20150915170743.16"><vh>h2</vh></v>
<v t="amd.20150915170743.17"><vh>h2</vh></v>
<v t="amd.20150915170743.18"><vh>h2</vh></v>
<v t="amd.20150915170743.19"><vh>markdown 頁面</vh></v>
<v t="amd.20150915170743.20" a="E"><vh>h2</vh>
<v t="amd.20150915170743.21"><vh>Fragement 主頁面</vh></v>
<v t="amd.20150915170743.22" a="E"><vh>下屬頁面</vh>
<v t="amd.20150915170743.23"><vh>h2</vh></v>
<v t="amd.20150915170743.24"><vh>p</vh></v>
<v t="amd.20150915170743.25"><vh>p</vh></v>
<v t="amd.20150915170743.26"><vh>p</vh></v>
<v t="amd.20150915170743.27"><vh>p</vh></v>
<v t="amd.20150915170743.28"><vh>p</vh></v>
<v t="amd.20150915170743.29"><vh>p</vh></v>
<v t="amd.20150915170743.30"><vh>p</vh></v>
</v>
</v>
<v t="amd.20150915170743.31"><vh>h2</vh></v>
<v t="amd.20150915170743.32"><vh>p</vh>
<v t="amd.20150915170743.33"><vh>a</vh></v>
<v t="amd.20150915170743.34"><vh>a</vh></v>
<v t="amd.20150915170743.35"><vh>a</vh></v>
<v t="amd.20150915170743.36"><vh>a</vh></v>
<v t="amd.20150915170743.37"><vh>a</vh></v>
<v t="amd.20150915170743.38"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.39"><vh>h2 - 更換主題</vh></v>
<v t="amd.20150915170743.40" a="E"><vh>p</vh>
<v t="amd.20150915170743.41"><vh>a</vh></v>
<v t="amd.20150915170743.42"><vh>a</vh></v>
<v t="amd.20150915170743.43"><vh>a</vh></v>
<v t="amd.20150915170743.44"><vh>a</vh></v>
<v t="amd.20150915170743.45"><vh>a</vh></v>
<v t="amd.20150915170743.46"><vh>a</vh></v>
<v t="amd.20150915170743.47"><vh>a</vh></v>
<v t="amd.20150915170743.48"><vh>a</vh></v>
<v t="amd.20150915170743.49"><vh>a</vh></v>
<v t="amd.20150915170743.50"><vh>a</vh></v>
<v t="amd.20150915170743.51"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.52"><vh>h2</vh></v>
<v t="amd.20150915170743.53"><vh>p</vh>
<v t="amd.20150915170743.54"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.55"><vh>a</vh></v>
<v t="amd.20150915170743.56"><vh>h2</vh></v>
<v t="amd.20150915170743.57" a="E"><vh>pre</vh>
<v t="amd.20150915170743.58"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.59"><vh>h2 - 背景填圖頁面</vh></v>
<v t="amd.20150915170743.60" a="E"><vh>pre</vh>
<v t="amd.20150915170743.61"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.62" a="E"><vh>div</vh>
<v t="amd.20150915170743.63"><vh>h2</vh></v>
<v t="amd.20150915170743.64"><vh>pre</vh>
<v t="amd.20150915170743.65"><vh>code</vh></v>
</v>
</v>
<v t="amd.20150915170743.66"><vh>h2</vh></v>
<v t="amd.20150915170743.67"><vh>h2</vh></v>
<v t="amd.20150915170743.68"><vh>p</vh></v>
<v t="amd.20150915170743.69"><vh>pre</vh>
<v t="amd.20150915170743.70"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.71"><vh>h2 - 背景轉換</vh></v>
<v t="amd.20150915170743.72"><vh>p</vh></v>
<v t="amd.20150915170743.73" a="E"><vh>pre</vh>
<v t="amd.20150915170743.74"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.75" a="E"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915170743.76" a="E"><vh>pre</vh>
<v t="amd.20150915170743.77"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.78"><vh>p</vh></v>
</v>
<v t="amd.20150915170743.79"><vh>h2</vh></v>
<v t="amd.20150915170743.80" a="E"><vh>ul</vh>
<v t="amd.20150915170743.81"><vh>li</vh></v>
<v t="amd.20150915170743.82"><vh>li</vh></v>
<v t="amd.20150915170743.83"><vh>li</vh></v>
<v t="amd.20150915170743.84"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.85"><vh>h2</vh></v>
<v t="amd.20150915170743.86"><vh>ol</vh>
<v t="amd.20150915170743.87"><vh>li</vh></v>
<v t="amd.20150915170743.88"><vh>li</vh></v>
<v t="amd.20150915170743.89"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.90"><vh>h2 - 表格頁面</vh></v>
<v t="amd.20150915170743.91" a="E"><vh>table</vh>
<v t="amd.20150915170743.92"><vh>thead</vh>
<v t="amd.20150915170743.93"><vh>tr</vh>
<v t="amd.20150915170743.94"><vh>th</vh></v>
<v t="amd.20150915170743.95"><vh>th</vh></v>
<v t="amd.20150915170743.96"><vh>th</vh></v>
</v>
</v>
<v t="amd.20150915170743.97"><vh>tbody</vh>
<v t="amd.20150915170743.98"><vh>tr</vh>
<v t="amd.20150915170743.99"><vh>td</vh></v>
<v t="amd.20150915170743.100"><vh>td</vh></v>
<v t="amd.20150915170743.101"><vh>td</vh></v>
</v>
<v t="amd.20150915170743.102"><vh>tr</vh>
<v t="amd.20150915170743.103"><vh>td</vh></v>
<v t="amd.20150915170743.104"><vh>td</vh></v>
<v t="amd.20150915170743.105"><vh>td</vh></v>
</v>
<v t="amd.20150915170743.106"><vh>tr</vh>
<v t="amd.20150915170743.107"><vh>td</vh></v>
<v t="amd.20150915170743.108"><vh>td</vh></v>
<v t="amd.20150915170743.109"><vh>td</vh></v>
</v>
</v>
</v>
<v t="amd.20150915170743.110"><vh>h2</vh></v>
<v t="amd.20150915170743.111"><vh>p</vh>
<v t="amd.20150915170743.112"><vh>q</vh></v>
</v>
<v t="amd.20150915170743.113"><vh>blockquote</vh></v>
<v t="amd.20150915170743.114"><vh>h2</vh></v>
<v t="amd.20150915170743.115"><vh>p</vh>
<v t="amd.20150915170743.116"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.117"><vh>h2</vh></v>
<v t="amd.20150915170743.118" a="E"><vh>p</vh>
<v t="amd.20150915170743.119"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.120"><vh>p</vh>
<v t="amd.20150915170743.121"><vh>em</vh></v>
</v>
<v t="amd.20150915170743.122"><vh>h2</vh></v>
<v t="amd.20150915170743.123"><vh>p</vh>
<v t="amd.20150915170743.124"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.125"><vh>iframe</vh></v>
<v t="amd.20150915170743.126"><vh>h2</vh></v>
<v t="amd.20150915170743.127" a="E"><vh>p</vh>
<v t="amd.20150915170743.128"><vh>code</vh></v>
<v t="amd.20150915170743.129"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.130"><vh>h2</vh></v>
<v t="amd.20150915170743.131"><vh>p</vh>
<v t="amd.20150915170743.132"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.133"><vh>pre</vh>
<v t="amd.20150915170743.134"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.135"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="amd.20150915170743.136"><vh>p</vh></v>
<v t="amd.20150915170743.137" a="E"><vh>h2 unordered list 頁面</vh>
<v t="amd.20150915170743.138"><vh>li</vh>
<v t="amd.20150915170743.139"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.140"><vh>li</vh>
<v t="amd.20150915170743.141"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.142"><vh>li</vh>
<v t="amd.20150915170743.143"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.144"><vh>li</vh>
<v t="amd.20150915170743.145"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.146"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.147"><vh>結束單頁</vh></v>
</v>
</v>
<v t="amd.20150915170743.148"><vh>script</vh></v>
<v t="amd.20150915170743.149"><vh>script</vh></v>
<v t="amd.20150915170743.150"><vh>script</vh></v>
</v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="amd.20150913232631.1"></t>
<t tx="amd.20150913232631.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="amd.20150913232631.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="amd.20150913233943.1">@language xml
@tabwidth -4
@others
</t>
<t tx="amd.20150913233943.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150913233943.3">
&lt;head&gt;
@others
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;    
    &lt;!--Add support for earlier versions of Internet Explorer --&gt;
    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;
 
</t>
<t tx="amd.20150913233943.4">
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015 Fall CADP B Week1&lt;/title&gt;
</t>
<t tx="amd.20150913233943.5">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150913233943.6">
&lt;!-- Wrap the entire slide show in a div using the "reveal" class. --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150913233943.7">
&lt;!-- Wrap all slides in a single "slides" class --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150913233943.81">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
    </t>
<t tx="amd.20150913233943.82">&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
 
    </t>
<t tx="amd.20150913233943.83">&lt;script&gt;
        // Required, even if empty.
        Reveal.initialize({
        });
    &lt;/script&gt;
</t>
<t tx="amd.20150913234947.1">&lt;section id="title page"&gt;
&lt;section&gt;
標題頁面
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="amd.20150913235034.1">&lt;section&gt;
本日要點
&lt;/section&gt;</t>
<t tx="amd.20150913235123.1">&lt;section&gt;
結論
&lt;/section&gt;</t>
<t tx="amd.20150913235225.1">&lt;section&gt;
標題頁下的子頁
&lt;/section&gt;</t>
<t tx="amd.20150914000138.1">&lt;section&gt;
&lt;a href="http://continuum.io/downloads"&gt;Anaconda Python 下載&lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150914000332.1">&lt;section id="設計的表達方式"&gt;
&lt;section&gt;
設計的表達方式
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="amd.20150914000332.2">&lt;section&gt;
協同模式下的網際雲端內容呈現
&lt;/section&gt;</t>
<t tx="amd.20150915153206.1">2015.09.15

將 2014 的 index.html 與 cadpbw1.html 與 2015 最新的 reveal 框架檔案合併
此後將以 v31ref.html 中的語法為主

</t>
<t tx="amd.20150915155634.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915155634.10">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915155634.100">
&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="amd.20150915155634.101">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="amd.20150915155634.102">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="amd.20150915155634.103">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="amd.20150915155634.104">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915155634.105">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="amd.20150915155634.106">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.107">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.108">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="amd.20150915155634.109">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="amd.20150915155634.11">&lt;section id="fragments"&gt;
        &lt;h1&gt;課程說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;課程名稱: 電腦輔助設計實習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;開放 主動 自學與自評&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;使用 Solvespace 與 Creo 2.0&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;每週都有作業, 由各學員自評分數&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915155634.110">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.111">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.112">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="amd.20150915155634.113">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="amd.20150915155634.114">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.115">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.116">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.117">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.118">
These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="amd.20150915155634.119">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.12">&lt;section id="fragments"&gt;
    &lt;h2&gt;實體輔助工具&lt;/h2&gt;
    &lt;h3 class="fragment"&gt;電動折疊自行車&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;HP 伺服器&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;3D 印表機零件&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;其他需要採購工具?&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;先模擬分析, 再實際驗證?&lt;/h3&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.120">&lt;section&gt;
&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.121">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915155634.122">
You can link between slides internally,
&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
</t>
<t tx="amd.20150915155634.123">&lt;section&gt;
&lt;h2&gt;Speaker View&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.124">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.125">There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.</t>
<t tx="amd.20150915155634.126">&lt;p&gt;
@others
&lt;/p&gt;
    &lt;aside class="notes"&gt;
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
    &lt;/aside&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.127">Press the &lt;em&gt;S&lt;/em&gt; key to try it out.</t>
<t tx="amd.20150915155634.128">&lt;section&gt;
&lt;h2&gt;Export to PDF&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.129">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.13">&lt;section&gt;
@others
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.130">Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:</t>
<t tx="amd.20150915155634.131">&lt;iframe src="//www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.132">&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.133">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.134">Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and </t>
<t tx="amd.20150915155634.135">&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
					</t>
<t tx="amd.20150915155634.136">&lt;section data-state="customevent"&gt;
&lt;h2&gt;State Events&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.137">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.138">
Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
</t>
<t tx="amd.20150915155634.139">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.14">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915155634.140">&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;</t>
<t tx="amd.20150915155634.141">&lt;section&gt;
&lt;h2&gt;Take a Moment&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.142">&lt;p&gt;
Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915155634.143">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.145">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="amd.20150915155634.146">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.147">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="amd.20150915155634.148">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.149">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="amd.20150915155634.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.150">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.151">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="amd.20150915155634.152">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.153">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="amd.20150915155634.154">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;section&gt;
					</t>
<t tx="amd.20150915155634.158">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
		</t>
<t tx="amd.20150915155634.159">&lt;script src="js/reveal.js"&gt;&lt;/script&gt;

		</t>
<t tx="amd.20150915155634.16">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.160">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="amd.20150915155634.17">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.18">&lt;section&gt;
    &lt;h2&gt;Point of View&lt;/h2&gt;
    &lt;p&gt;
    Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
    &lt;/p&gt;
    &lt;p&gt;
    Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.19">&lt;section&gt;
    &lt;h2&gt;Touch Optimized&lt;/h2&gt;
    &lt;p&gt;
    Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150915155634.20">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="amd.20150915155634.21">&lt;section&gt;
    @others
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.28">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="amd.20150915155634.29">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.3">&lt;head&gt;
@others
&lt;/head&gt;

</t>
<t tx="amd.20150915155634.30">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.31">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.32">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.33">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.34">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.35">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="amd.20150915155634.36">&lt;section id="transitions"&gt;
&lt;h2&gt;Transition Styles&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.37">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.38">
You can select from different transitions, like: &lt;br&gt;
&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
</t>
<t tx="amd.20150915155634.39">&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.4">&lt;meta charset="utf-8"&gt;

&lt;title&gt;2015 Fall 電腦輔助設計實習 甲班&lt;/title&gt;

</t>
<t tx="amd.20150915155634.40">&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.41">&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.42">&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.43">&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					</t>
<t tx="amd.20150915155634.44">&lt;section id="themes"&gt;
&lt;h2&gt;Themes&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.45">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						</t>
<t tx="amd.20150915155634.46">
reveal.js comes with a few themes built in: &lt;br&gt;
&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
</t>
<t tx="amd.20150915155634.47">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.48">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.49">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.5">&lt;meta name="description" content="2015Fall CADP"&gt;
&lt;meta name="author" content="KMOL"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
		</t>
<t tx="amd.20150915155634.50">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.51">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; </t>
<t tx="amd.20150915155634.52">&lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.53">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.54">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.55">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.56">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					</t>
<t tx="amd.20150915155634.57">&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.58">&lt;p&gt;
@others
&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.59">
Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
</t>
<t tx="amd.20150915155634.60">&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						</t>
<t tx="amd.20150915155634.61">&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.62">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.63">&lt;code&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.64">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.65">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						</t>
<t tx="amd.20150915155634.66">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
&lt;/code&gt;</t>
<t tx="amd.20150915155634.67">&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
@others
&lt;/div&gt;
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.68">&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
</t>
<t tx="amd.20150915155634.69">&lt;pre&gt;
@others
&lt;/pre&gt;
						</t>
<t tx="amd.20150915155634.7">&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
	</t>
<t tx="amd.20150915155634.70">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.71">&lt;h2&gt;... and GIFs!&lt;/h2&gt;
&lt;/section&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.72">&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.73">&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.74">&lt;pre&gt;
@others
&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					</t>
<t tx="amd.20150915155634.75">&lt;code&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;</t>
<t tx="amd.20150915155634.76">&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.77">&lt;p&gt;
You can override background transitions per-slide.
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.78">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.79">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.8">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915155634.80">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.81">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915155634.82">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915155634.83">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915155634.85">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.86">&lt;ul&gt;
@others
&lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.87">
&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="amd.20150915155634.88">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.89">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.9">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915155634.90">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.91">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.92">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="amd.20150915155634.93">
&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="amd.20150915155634.94">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.95">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.96">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.97">&lt;table&gt;
@others
&lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.98">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="amd.20150915155634.99">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915160450.1">&lt;section id="fragments"&gt;
&lt;h2&gt;Fragments&lt;/h2&gt;
&lt;p&gt;Hit the next arrow...&lt;/p&gt;
&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
&lt;p&gt;
    &lt;span class="fragment"&gt;... a&lt;/span&gt; 
    &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
    &lt;span class="fragment"&gt;slide.&lt;/span&gt;
&lt;/p&gt;

&lt;aside class="notes"&gt;
This slide has fragments which are also stepped through in the notes window.
&lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915161424.1">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="amd.20150915170743.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915170743.10">&lt;section&gt;
        &lt;h1&gt;Reveal.js 使用說明&lt;/h1&gt;
    &lt;h3&gt;The HTML Presentation Framework 框架&lt;/h3&gt;
    &lt;p&gt;
    &lt;small&gt;
    Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / 
    &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;
    &lt;/small&gt;
    &lt;/p&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915170743.100">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.101">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.102">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="amd.20150915170743.103">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="amd.20150915170743.104">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.105">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.106">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="amd.20150915170743.107">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="amd.20150915170743.108">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.109">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.11">&lt;section&gt;
    &lt;h2&gt;Hello There&lt;/h2&gt;
    &lt;p&gt;
reveal.js enables you to create beautiful interactive slide decks using HTML. This presentation will show you examples of what it can do.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.110">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.111">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.112">
These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="amd.20150915170743.113">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.114">&lt;section&gt;
&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.115">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915170743.116">
You can link between slides internally,
&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
</t>
<t tx="amd.20150915170743.117">&lt;section&gt;
&lt;h2&gt;Speaker View&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.118">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.119">There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.</t>
<t tx="amd.20150915170743.12">&lt;section&gt;
@others
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.120">&lt;p&gt;
@others
&lt;/p&gt;
    &lt;aside class="notes"&gt;
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
    &lt;/aside&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.121">Press the &lt;em&gt;S&lt;/em&gt; key to try it out.</t>
<t tx="amd.20150915170743.122">&lt;section&gt;
&lt;h2&gt;Export to PDF&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.123">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.124">Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:</t>
<t tx="amd.20150915170743.125">&lt;iframe src="//www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.126">&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.127">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.128">Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and </t>
<t tx="amd.20150915170743.129">&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
					</t>
<t tx="amd.20150915170743.13">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915170743.130">&lt;section data-state="customevent"&gt;
&lt;h2&gt;State Events&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.131">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.132">
Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
</t>
<t tx="amd.20150915170743.133">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.134">&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;</t>
<t tx="amd.20150915170743.135">&lt;section&gt;
&lt;h2&gt;Take a Moment&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.136">&lt;p&gt;
Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915170743.137">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.138">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.139">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="amd.20150915170743.14">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.140">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.141">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="amd.20150915170743.142">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.143">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="amd.20150915170743.144">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.145">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="amd.20150915170743.146">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="amd.20150915170743.147">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;section&gt;
					</t>
<t tx="amd.20150915170743.148">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
		</t>
<t tx="amd.20150915170743.149">&lt;script src="js/reveal.js"&gt;&lt;/script&gt;

		</t>
<t tx="amd.20150915170743.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.150">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="amd.20150915170743.16">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.17">&lt;section&gt;
    &lt;h2&gt;Point of View&lt;/h2&gt;
    &lt;p&gt;
    Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
    &lt;/p&gt;
    &lt;p&gt;
    Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.18">&lt;section&gt;
    &lt;h2&gt;Touch Optimized&lt;/h2&gt;
    &lt;p&gt;
    Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.19">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="amd.20150915170743.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150915170743.20">&lt;section&gt;
    @others
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.21">&lt;section id="fragments"&gt;
&lt;h2&gt;Fragments&lt;/h2&gt;
&lt;p&gt;Hit the next arrow...&lt;/p&gt;
&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
&lt;p&gt;
    &lt;span class="fragment"&gt;... a&lt;/span&gt; 
    &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
    &lt;span class="fragment"&gt;slide.&lt;/span&gt;
&lt;/p&gt;

&lt;aside class="notes"&gt;
This slide has fragments which are also stepped through in the notes window.
&lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915170743.22">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="amd.20150915170743.23">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="amd.20150915170743.24">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.25">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.26">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.27">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.28">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.29">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.3">&lt;head&gt;
@others
&lt;/head&gt;

</t>
<t tx="amd.20150915170743.30">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="amd.20150915170743.31">&lt;section id="transitions"&gt;
&lt;h2&gt;Transition Styles&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.32">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.33">
You can select from different transitions, like: &lt;br&gt;
&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
</t>
<t tx="amd.20150915170743.34">&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.35">&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.36">&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.37">&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.38">&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					</t>
<t tx="amd.20150915170743.39">&lt;section id="themes"&gt;
&lt;h2&gt;Themes&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.4">&lt;meta charset="utf-8"&gt;

&lt;title&gt;reveal.js - The HTML Presentation Framework&lt;/title&gt;

</t>
<t tx="amd.20150915170743.40">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						</t>
<t tx="amd.20150915170743.41">
reveal.js comes with a few themes built in: &lt;br&gt;
&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
</t>
<t tx="amd.20150915170743.42">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.43">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.44">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.45">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.46">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; </t>
<t tx="amd.20150915170743.47">&lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.48">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.49">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.5">&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
&lt;meta name="author" content="Hakim El Hattab"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
		</t>
<t tx="amd.20150915170743.50">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.51">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					</t>
<t tx="amd.20150915170743.52">&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915170743.53">&lt;p&gt;
@others
&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.54">
Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
</t>
<t tx="amd.20150915170743.55">&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						</t>
<t tx="amd.20150915170743.56">&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915170743.57">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.58">&lt;code&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915170743.59">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915170743.6">&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
	</t>
<t tx="amd.20150915170743.60">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						</t>
<t tx="amd.20150915170743.61">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
&lt;/code&gt;</t>
<t tx="amd.20150915170743.62">&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
@others
&lt;/div&gt;
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.63">&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
</t>
<t tx="amd.20150915170743.64">&lt;pre&gt;
@others
&lt;/pre&gt;
						</t>
<t tx="amd.20150915170743.65">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915170743.66">&lt;h2&gt;... and GIFs!&lt;/h2&gt;
&lt;/section&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.67">&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.68">&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.69">&lt;pre&gt;
@others
&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					</t>
<t tx="amd.20150915170743.7">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915170743.70">&lt;code&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;</t>
<t tx="amd.20150915170743.71">&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.72">&lt;p&gt;
You can override background transitions per-slide.
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.73">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.74">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915170743.75">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.76">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915170743.77">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915170743.78">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915170743.79">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.8">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915170743.80">&lt;ul&gt;
@others
&lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.81">
&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="amd.20150915170743.82">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.83">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.84">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.85">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.86">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="amd.20150915170743.87">
&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="amd.20150915170743.88">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.89">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.9">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915170743.90">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.91">&lt;table&gt;
@others
&lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.92">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="amd.20150915170743.93">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915170743.94">
&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="amd.20150915170743.95">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="amd.20150915170743.96">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="amd.20150915170743.97">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="amd.20150915170743.98">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915170743.99">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="amd.20150915172241.1">&lt;section id="fragments"&gt;
        &lt;h1&gt;自評說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;時效內的 Github 倉儲內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;完全開放的學員作業內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;彼此間可以互相學習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;存證內容: Github, copy.com, Vimeo 等&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;要怎麼收穫, 先怎麼栽!&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915173703.1">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915173703.2">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915173703.3">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915173703.4">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915204710.1">&lt;section&gt;
&lt;h1&gt;嵌入 Vimeo 影片&lt;/h1&gt;
&lt;iframe src="https://player.vimeo.com/video/137724068" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt; &lt;p&gt;&lt;a href="https://vimeo.com/137724068"&gt;Welcome Speech&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程系 KMOL&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915211341.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915211351.1">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="amd.20150915211351.12">&lt;section&gt;
    &lt;h1&gt;第3張投影片&lt;/h1&gt;
    &lt;p&gt;成績自評分數的量化依據?&lt;/p&gt;
    &lt;p&gt;可以連結到內部投影片&lt;a href="#/hw-task-one"&gt;作業任務一&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="amd.20150915211351.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="amd.20150915211351.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915211351.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;有關我的作業&lt;/h1&gt;
    &lt;p&gt;學號姓名與日期&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="amd.20150915211351.9">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;作業任務一&lt;/h1&gt;
    &lt;p&gt;有關作業任務一的說明&lt;/p&gt;
    &lt;p&gt;請參考 &lt;a href="http://www.google.com"&gt;Google&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="amd.20150917085040.1">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="amd.20150919102209.1">本專案

利用 Jupyter 產生 IPython notebook, 然後整合入 pelican 網誌

利用 github pages 在 github.io 網站上伺服網頁資料

利用 reveal.js 產生投影片

利用 pelican 與 Markdown 產生網誌文章

利用 disqus 建立互動留言系統</t>
<t tx="amd.20150919102541.1">在 Anaconda 3 中只要

    pip install pelican Markdown 

安裝 pelican 與 Markdown Python 模組即可

若是在 Ubuntu 中則可以透過

    sudo pip3 install pelican Markdown 

安裝 pelican 與 Markdown Python 模組</t>
<t tx="amd.20150919102739.1">主要為 reveal.js 的簡報目錄架構, 其他子目錄為

images - 存放簡報與 pelican 網誌所需要的影像檔案

pelican - 存放 pelican 專案資料檔, 並且設法讓 pelican 所產生的 output 檔案直接存放到上層 reveal.js 根目錄

notebook - 存放 Jupyter 的 IPython notebook 檔案, 然後再由 pelican 設定, 將內容放入 blog 文章中

</t>
<t tx="amd.20150919103341.1">REM start.bat 中 取電腦 IP 與 Jupyter 啟動

REM 取 IPV4 IP address
for /f "delims=[] tokens=2" %%a in ('ping -4 %computername% -n 1 ^| findstr "["') do (set thisip=%%a)
REM echo %thisip%
REM 取 IPV6 IP address
REM for /f "delims=[] tokens=2" %%a in ('ping %computername% -n 1 ^| findstr "["') do (set thisip=%%a)
REM echo %thisip%
REM 啟動 Jupyter
cd notebook
start %Disk%:\Anaconda3\python.exe "%Disk%:\Anaconda3\Scripts\ipython-script.py" notebook --ip=%thisip% --certfile=%Disk%:\home\ssl_cert.pem --profile=nbserver</t>
<t tx="amd.20150919103357.1">打算利用

pelican pelican -o ./../ -s publishconf.py

-o 指定 ouput 所在目錄, 這裡使用上一層目錄, 

-s 則指定 setting, 這裡採用 publishconf.py 中的設定

將位於專案中 pelican 目錄內的 .md 檔案, 轉為 html 網誌格式, 然後存在 reveal.js 的架構目錄中

也就是 index.html 是由 pelican 控制</t>
<t tx="amd.20150919103428.1"></t>
<t tx="amd.20150919103923.1">home/.ipython/profile_nbserver/ipython_notebook_config.py

內容為:

# Password to use for web authentication
c = get_config()
# password is  "2015cp"
c.NotebookApp.password = u'sha1:864c0bcdb94e:8a396ef692ef3cc552177f1b1c48cec70c7a32df'
c.NotebookApp.port = 8888

產生 password 的程式碼:

from IPython.lib import passwd
passwd()

</t>
<t tx="amd.20150919104249.1">@language python
# show 出 ipython notebook 所使用的 profile 目錄
# 這裡應該會傳回 {'location': 'y:\\home\\.ipython\\profile_nbserver'}
# 表示 custom.js 位於 'y:\\home\\.ipython\\profile_nbserver\\static\\custom'
'''在 custom.js 中加入
require(["base/js/events"], function (events) {
    events.on("app_initialized.NotebookApp", function () {
    /* load your extension here */
    IPython.load_extensions('read-only');
    });
});
就可以自動導入'y:\\home\\.ipython\\nbextensions\read-only.js' 延伸檔案
read-only toggle 為 Alt+R
'''
# 以下為操作方法
'''當使用者選擇某一 cell, 然後按下 Alt+R, 則 cell 內原本為灰色將會變成白色, 表示
cell 為 read only
''''''
import IPython
ip=IPython.get_ipython()
ip.config.ProfileDir </t>
<t tx="amd.20150919112415.1">使用 Vimeo</t>
<t tx="amd.20150919112710.1"></t>
<t tx="amd.20150919113340.1"></t>
<t tx="amd.20150919113957.1"></t>
<t tx="amd.20150919114010.1"></t>
<t tx="amd.20150919120205.1"></t>
<t tx="amd.20150919124128.1">@language python
import os
os.system('''pelican pelican/content -o ./ -s pelican/publishconf.py -t theme/pelican-bootstrap3
''')
g.es("pelican 執行完畢")</t>
<t tx="amd.20150920030003.1">必須使用 IPython 3.2.1

sudo pip3 install IPython[notebook]==3.2.1

因為 IPython 4.0 已經將 IPython notebook 分出去改名為 Jupyter

之後可能再測試 liquid_tags 是否能與 Jupyter 相容</t>
<t tx="ibm.20150918175403.1">@language xml
@tabwidth -4
@others

</t>
<t tx="ibm.20150918175403.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	</t>
<t tx="ibm.20150918175403.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="ibm.20150918175403.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015CP W1&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="ibm.20150918175403.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="ibm.20150918175403.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="ibm.20150918175403.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="ibm.20150918175403.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;計算機程式&lt;/h1&gt;
    &lt;p&gt;第1週教學內容&lt;/p&gt;		
&lt;/section&gt;
	</t>
<t tx="ibm.20150918175403.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;課程規劃&lt;/h1&gt;
    &lt;p&gt;教科書&lt;/p&gt;
    &lt;p&gt;請參考 &lt;a href="http://openbookproject.net/thinkcs/python/english3e/"&gt;http://openbookproject.net/thinkcs/python/english3e/&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="ibm.20150918175403.9">&lt;section&gt;
    &lt;h1&gt;作業規劃&lt;/h1&gt;
    &lt;p&gt;影片內容&lt;/p&gt;
    &lt;a href="https://www.youtube.com/watch?v=9uq3w6JJS00"&gt;Zero to hero with Python&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="ibm.20150918175711.1">&lt;section&gt;
    &lt;h1&gt;Git 操作&lt;/h1&gt;
    &lt;p&gt;git clone&lt;/p&gt;
    &lt;p&gt;git config --global user.name&lt;/p&gt;
    &lt;p&gt;git config --global user.email&lt;/p&gt;
    &lt;p&gt;git add -A&lt;/p&gt;
    &lt;p&gt;git commit -m&lt;/p&gt;
    &lt;p&gt;git push&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="ibm.20150918175951.1">&lt;section&gt;
    &lt;h1&gt;Jupyter 操作&lt;/h1&gt;
    &lt;p&gt;啟動&lt;/p&gt;
    &lt;p&gt;基本執行&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="ibm.20150918181528.1">&lt;section&gt;
    &lt;h1&gt;結論&lt;/h1&gt;
    &lt;p&gt;自主開放學習&lt;/p&gt;
    &lt;p&gt;線上教材&lt;/p&gt;
    &lt;p&gt;影音教材&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="leo.20151116214200.1"></t>
<t tx="leo.20151116214200.10">@language html
&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40423203-8&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;zero to hero python教學&lt;/h1&gt;
    &lt;p&gt;40423203 四設一乙 &lt;/p&gt;		
&lt;/section&gt;
	
&lt;section id="hw-task-five"&gt;
    &lt;h1&gt;作業八-任務說明&lt;/h1&gt;
    &lt;p&gt;&lt;/p&gt;   
&lt;/section&gt;



&lt;section&gt;
&lt;h1&gt;自評&lt;/h1&gt;
&lt;/section&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
&lt;/body&gt;

</t>
<t tx="leo.20151116214200.11">@language html
&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40423203-9&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;zero to hero python教學&lt;/h1&gt;
    &lt;p&gt;40423203 四設一乙 &lt;/p&gt;		
&lt;/section&gt;
	
&lt;section id="hw-task-five"&gt;
    &lt;h1&gt;作業九-任務說明&lt;/h1&gt;
    &lt;p&gt;&lt;/p&gt;   
&lt;/section&gt;
  
  &lt;section&gt;
&lt;h1&gt;期中報告心得&lt;/h1&gt;
計算機程式!!是什麼課?!在上這堂課之前心中充滿疑問。老師口中滿滿的專業術語,從Python,Jupyter到Github等等,都是從來沒接觸過的,在第堂課申請了Github的帳號,只是聽老師一個口令一個動作,完全不了解何謂Github。另外還說了字串,是什麼啊?!第一堂課就如此困難。在接下來的課程中教得越來越多,步調越來越快,跟都跟不上,好慌張啊!!
&lt;/section&gt; 

  &lt;section&gt;
終於在第六週時跟上了步調,但卻因為餔知如何上推至遠端的全班偕同倉儲止步了。全班偕同倉儲真是一個好用的東西,但前提是必須熟悉操作流程。第七週,老師做了個總結,使我更加了解自己的不足,在這個網路蓬勃發展的世代,我悶應善加利用網路,而非用來玩樂。第八週了,學校網路出現了問題,老師對此做了說明"我們準備好要使用IPV6了嗎?,雖然不是非常了解,但仍努力吸收消化中。
&lt;/section&gt; 

&lt;section&gt;
第九週了,不能再廢下去了,與同學深入研究這幾個月所學,從早上9:00到隔天的凌晨5:00,將每週上課所錄的影片看了又看,同學一個問過一個,終於了解了,並將這幾個月上課的心得與功課成功上推至遠端偕同倉儲,且拍了兩個無聲的操作影片,並對自己的努力做了個結論。
&lt;/section&gt; 

&lt;section&gt;
&lt;h1&gt;自評&lt;/h1&gt;
從一開始的什麼都不懂,到現在能夠自行賞推功課至遠端全班偕同倉儲,非常開心。在第九週終於有了明顯的進步,並且錄了"從近端推送至遠端"的無聲影片,我想我不只完成了老師交代的作業,更完成了對自己負責的態度,不是找打手,而是從無到有的學習。給自己的分數是:75分。
&lt;/section&gt; 
&lt;/div&gt;
&lt;/div&gt;
&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
&lt;/body&gt;

</t>
<t tx="leo.20151116214200.12"></t>
<t tx="leo.20151116214200.13"></t>
<t tx="leo.20151116214200.14">@language python
#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

# This file is only used if you use `make publish` or
# explicitly specify it as your config file.

import os

AUTHOR = '40423203'
SITENAME = '2015FALL 40423203 CPB 作業'
SITEURL = ''

PATH = 'content'

TIMEZONE = 'Asia/Taipei'

DEFAULT_LANG = 'en'

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Blogroll
LINKS = (('2015課程網頁', 'http://wordpress-2015course.rhcloud.com/'),
         ('Python', 'http://python.org/'),('2015作業主頁', '../../'),
         ('40423203倉儲', '40423203github.io.cpbtest2'))

# Social widget
SOCIAL = (('twitter', 'http://twitter.com/ametaireau'),
          ('github', 'http://github.com/ametaireau'),)
          
DEFAULT_PAGINATION = 10

SITEURL = 'http://coursemdetw.github.io/reveal'
RELATIVE_URLS = True

FEED_ALL_ATOM = 'feeds/all.atom.xml'
CATEGORY_FEED_ATOM = 'feeds/%s.atom.xml'

DELETE_OUTPUT_DIRECTORY = True

# Following items are often useful when publishing

#DISQUS_SITENAME = ""
DISQUS_SITENAME = "2015fall"
#GOOGLE_ANALYTICS = ""

# 必須絕對目錄或相對於設定檔案所在目錄
PLUGIN_PATHS = ['./../../../plugin']
PLUGINS = ['liquid_tags.notebook']
# 目錄設定相對於 reveal 下的 content 目錄
NOTEBOOK_DIR = 'notebook'


</t>
<t tx="leo.20151116214200.15"></t>
<t tx="leo.20151116214200.16"></t>
<t tx="leo.20151116214200.17">@language md
Title: 2015 計算機程式 作業ㄧ
Date: 2015-9/18 10:41
Category: Python
Tags: pelican, publishing
Slug: 2015cp_hw_w1
Authors: 40423203
Summary: 作業ㄧ摘要

以下為作業ㄧ內容

利用 iframe 嵌入投影片:

&lt;iframe src="40423203_cp_w1_p.html" width="500" height="300"&gt;&lt;/iframe&gt;

[作業四投影片](40423203_cp_w1_p.html){:target="_blank"}</t>
<t tx="leo.20151116214200.18">@language md
Title: 2015 計算機程式 作業二
Date: 2015-9/25 2:36
Category: Python
Tags: pelican, publishing
Slug: 2015cp_hw_w2
Authors: 40423203
Summary: 作業二摘要

以下為作業二內容

利用 iframe 嵌入投影片:

&lt;iframe src="40423203_cp_w2_p.html" width="500" height="300"&gt;&lt;/iframe&gt;

[作業投影片](40423203_cp_w2_p.html){:target="_blank"}</t>
<t tx="leo.20151116214200.19">@language md
Title: 2015 計算機程式 作業三
Date: 2015-10/2 2:36
Category: Python
Tags: pelican, publishing
Slug: 2015cp_hw_w3
Authors: 40423203
Summary: 作業三摘要

以下為作業三內容

利用 iframe 嵌入投影片:

&lt;iframe src="40423203_cp_w3_p.html" width="500" height="300"&gt;&lt;/iframe&gt;

[作業投影片](40423203_cp_w3_p.html){:target="_blank"}</t>
<t tx="leo.20151116214200.2"></t>
<t tx="leo.20151116214200.20">@language md
Title: 2015 計算機程式 作業四
Date: 2015-10/9 2:36
Category: Python
Tags: pelican, publishing
Slug: 2015cp_hw_w4
Authors: 40423203
Summary: 作業四摘要

以下為作業四內容

利用 iframe 嵌入投影片:

&lt;iframe src="40423203_cp_w4_p.html" width="500" height="300"&gt;&lt;/iframe&gt;

[作業投影片](40423203_cp_w4_p.html){:target="_blank"}</t>
<t tx="leo.20151116214200.21">@language md
Title: 2015 計算機程式 作業五
Date: 2015-10/16 2:36
Category: Python
Tags: pelican, publishing
Slug: 2015cp_hw_w5
Authors: 40423203
Summary: 作業五摘要

以下為作業五內容

利用 iframe 嵌入投影片:

&lt;iframe src="40423203_cp_w5_p.html" width="500" height="300"&gt;&lt;/iframe&gt;

[作業投影片](40423203_cp_w5_p.html){:target="_blank"}</t>
<t tx="leo.20151116214200.22">@language md
Title: 2015 計算機程式 作業六
Date: 2015-10/30 2:36
Category: Python
Tags: pelican, publishing
Slug: 2015cp_hw_w6
Authors: 40423203
Summary: 作業六摘要

以下為作業六內容

利用 iframe 嵌入投影片:

&lt;iframe src="40423203_cp_w6_p.html" width="500" height="300"&gt;&lt;/iframe&gt;

[作業投影片](40423203_cp_w6_p.html){:target="_blank"}

&lt;iframe src="https://player.vimeo.com/video/144983217" width="500" height="313" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt; &lt;p&gt;&lt;a href="https://vimeo.com/144983217"&gt;第六週計算機程式操作bandicam 2015-11-08 00-13-29-035&lt;/a&gt; from &lt;a href="https://vimeo.com/user45597735"&gt;40423201&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;</t>
<t tx="leo.20151116214200.23">@language md
Title: 2015 計算機程式 作業七
Date: 2015-11/06 2:36
Category: Python
Tags: pelican, publishing
Slug: 2015cp_hw_w7
Authors: 40423203
Summary: 作業七摘要

以下為作業七內容

利用 iframe 嵌入投影片:

&lt;iframe src="40423203_cp_w7_p.html" width="500" height="300"&gt;&lt;/iframe&gt;

[作業投影片](40423203_cp_w7_p.html){:target="_blank"}</t>
<t tx="leo.20151116214200.24">@language md
Title: 2015 計算機程式 作業八
Date: 2015-11/06 2:36
Category: Python
Tags: pelican, publishing
Slug: 2015cp_hw_w8
Authors: 40423203
Summary: 作業八摘要

以下為作業八內容

利用 iframe 嵌入投影片:

&lt;iframe src="40423203_cp_w8_p.html" width="500" height="300"&gt;&lt;/iframe&gt;

[作業投影片](40423203_cp_w8_p.html){:target="_blank"}</t>
<t tx="leo.20151116214200.25">@language md
Title: 2015 計算機程式 作業九
Date: 2015-11/08 2:36
Category: Python
Tags: pelican, publishing
Slug: 2015cp_hw_w9
Authors: 40423203
Summary: 作業九摘要

以下為作業九內容

利用 iframe 嵌入投影片:

&lt;iframe src="40423203_cp_w9_p.html" width="500" height="300"&gt;&lt;/iframe&gt;

[作業投影片](40423203_cp_w9_p.html){:target="_blank"}

&lt;iframe src="https://player.vimeo.com/video/145030461" width="500" height="313" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt; &lt;p&gt;&lt;a href="https://vimeo.com/145030461"&gt;第九週計算機程式操作影片bandicam 2015-11-08 15-48-22-203&lt;/a&gt; from &lt;a href="https://vimeo.com/user45597735"&gt;40423201&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;</t>
<t tx="leo.20151116214200.3">@language html
&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;有關我的作業&lt;/h1&gt;
    &lt;p&gt;40423203 鄭惟芯&lt;/p&gt;		
&lt;/section&gt;
	
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;作業任務一&lt;/h1&gt;
    &lt;p&gt;課程內容介紹&lt;/p&gt;
    &lt;p&gt; &lt;a href="http://www.google.com"&gt;Google&lt;/a&gt;
&lt;/section&gt;
				
&lt;section&gt;
    &lt;h1&gt;心得&lt;/h1&gt;
    &lt;p&gt;第一次的上課,其中提到如何 print "hello"有好多種做法,並提到Github,感覺是門難懂的課,努力中。給自己的分數是:62&lt;/p&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;作業任務一&lt;/a&gt;
&lt;/section&gt;
				
&lt;/div&gt;
&lt;/div&gt;
&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
&lt;/body&gt;

</t>
<t tx="leo.20151116214200.4">@language html
&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40423201-2&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;zero to hero python教學 &lt;/h1&gt;
    &lt;p&gt;40423201 四設一乙&lt;/p&gt;		
&lt;/section&gt;
	
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;python?&lt;/h1&gt;
    &lt;p&gt;python是一種電腦語言,相較於其他電腦語言更為簡單,可以用來做計算,簡報,統計,甚至是管理倉儲,都可以利用python語法來完成,可以使用python語法的地方也不少,例如leo editor及matlab都是用python語法來運作,最重要的是,大部分的python軟體是免費的!&lt;/p&gt;
&lt;/section&gt;

&lt;section&gt;
&lt;h1&gt;怎麼樣的人適合學習python&lt;/h1&gt;
對程式設計陌生的人
&lt;br /&gt;
學生
&lt;br /&gt;
找工作的人
&lt;br /&gt;
IT PROS(從事資訊科技
的專業人員,information technology professionals)
&lt;br /&gt;
對程式語法有興趣的人
&lt;/section&gt;
&lt;section&gt;
&lt;h1&gt;一些簡單的語法:&lt;/h1&gt;

print:輸出
&lt;br /&gt;
在後面加一個小括弧跟引號,可以輸出引號內的內容:
&lt;br /&gt;
print("hello world")
&lt;br /&gt;
然後就可以得到:hello world!
&lt;/section&gt;
&lt;section&gt;
#:不作為語法
&lt;br /&gt;
不會把#後面的字串當作是程式語言,方便作為標註
&lt;br /&gt;
例如:#這是zero to hero第一回的介紹
&lt;/section&gt;
&lt;section&gt;
&lt;h1&gt;心得&lt;/h1&gt;
python是一種新主流!因為有協同所以大家不論有無網路都可以隨時做作業,且它不但免費又不像OFFICE那麼繁雜,是一個不可多得的好程式
&lt;/section&gt;
&lt;section&gt;
    &lt;h1&gt;自評&lt;/h1&gt;
    &lt;p&gt;作為一位工程師做創造的工作,了解到身為工程師所需的能力。一樣跟著老師做,但還是無法跟上,不停努力中。給自己的分數是: 63&lt;/p&gt;
&lt;/section&gt;
				
&lt;/div&gt;
&lt;/div&gt;
&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
&lt;/body&gt;

</t>
<t tx="leo.20151116214200.5">@language html
&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40423203-3&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;zero to hero python教學 &lt;/h1&gt;
    &lt;p&gt;40423203 四設一乙&lt;/p&gt;		
&lt;/section&gt;
	
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;引號的使用規則&lt;/h1&gt;
    &lt;p&gt;在前面我們學會了最簡單的輸出手段"print('___')",之後我們提到的是關於引號的使用,單引號跟雙引號其實都能把裡面的字做輸出,但不能任意的切換這兩個引號,這點在輸出英文字串的時候尤其需要注意&lt;/p&gt;
&lt;/section&gt;

&lt;section&gt;
如前面所說,我們輸入這兩個字串讓他運行,結果是一樣的:
&lt;/br&gt;
print("第二份作業")
&lt;/br&gt;
print('第二份作業')
&lt;/br&gt;
都可以得到"第二份作業"
&lt;/section&gt;
&lt;section&gt;
但我們絕對不允許混著用,例如:
&lt;/br&gt;
print("第二份作業')
&lt;/br&gt;
也盡量要避免在引號內使用引號,例如:
&lt;/br&gt;
print('I'm a student')
&lt;/br&gt;
這樣他會把框框指向I這個字上
&lt;/br&gt;
所以我們這個時候使用雙引號就可以避免這個衝突
&lt;/br&gt;
print("I'm a student")
&lt;/section&gt;

&lt;section&gt;
我們可以把兩個字串"相加"
&lt;br /&gt;
print("我正在"+"使用leo editor寫作業")
之後很明顯是得到:我正在使用leo editor寫作業
&lt;br /&gt;
也可以在引號間附上反斜線來達成空行的效果,例如:
&lt;/br&gt;
print("我的CAMSTUDIO/老是出狀況")
&lt;/br&gt;
得到:我的CAMSTUDIO
&lt;/br&gt;
老是出狀況
&lt;/br&gt;
還有個很特別的方法做空行:3個引號
&lt;/br&gt;
print("""我的CAMSTUDIO
&lt;/br&gt;
老是出狀況""")
得到的結果跟反斜線是一樣的
&lt;/section&gt;
&lt;section&gt;
&lt;h1&gt;心得&lt;/h1&gt;
Python:電腦語言看似深奧,但只要多做幾次之後就如同我們說的語言一樣流暢了。
上課 : 本週所學的是如何利用c:\現有的Ana3-2015工作,並介紹Python3的內容。包含Leo Editor 5.1,Pelican和Markdown模組。還有介紹如何製作reveal.js投影片。並了解cd的用法為"更換目錄", 存成.md檔 較人性化,適合人看。
&lt;/section&gt;
&lt;section&gt;
    &lt;h1&gt;自評&lt;/h1&gt;
    &lt;p&gt;第三週了,跟著老師的步驟做,但仍跟不上。要上台報告了!!非常的緊張,也不知道該說什麼,就把上課所抄的筆記念了一遍,做了一個不太清楚的結論,雖然不是很好,但我想至少上台報告時不是只有懺悔。給自己的分數是:64&lt;/p&gt;
&lt;/section&gt;
				
&lt;/div&gt;
&lt;/div&gt;
&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
&lt;/body&gt;

</t>
<t tx="leo.20151116214200.6">@language html
&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40423203-4&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;zero to hero python教學 &lt;/h1&gt;
    &lt;p&gt;40423203 四設一乙10/16&lt;/p&gt;		
&lt;/section&gt;
	
&lt;section id="hw-task-3"&gt;
    &lt;h1&gt;與python互動&lt;/h1&gt;
    &lt;p&gt;除了輸入字串讓python解讀之外,也可以輸入字串讓python進行簡單的互動劇情,核心指令為:input&lt;/p&gt;
&lt;/section&gt;

&lt;section&gt;
我們要讓python進入一個"問數學題目"的情境,可以輸入:
&lt;/br&gt;
x=input('2+2=')
&lt;/br&gt;
print(4)
&lt;/br&gt;
系統就會問你:
&lt;/br&gt;
2+2=
&lt;/br&gt;
之後不論你輸入什麼,他都會告訴你"4"
&lt;/section&gt;
&lt;section&gt;
不只是數學,甚至可以加入日常生活的對話,例如:
&lt;/br&gt;
x=input("what's your name?")
print("Hi"+x)
&lt;/br&gt;
就會先問你的名字,如果我打入"40423203"他就會顯示:
&lt;/br&gt;
Hi 40423203
&lt;/section&gt;

&lt;section&gt;
輸入多個代數也不是事,可以大膽地輸入
&lt;br /&gt;
x=input('給我一個數字代入x')
y=input('給我一個數字代入y')
print(2*x+3*y)
我們輸入x=2,y=1
&lt;/br&gt;
就能得到數字2x2+3x1=7
&lt;/section&gt;
&lt;section&gt;
當然,我們的開頭也有一些限制:
&lt;/br&gt;
1.最開頭不能是數字
&lt;/br&gt;
2.開頭不能有空白鍵
&lt;/br&gt;
3.大小寫的不同會視為兩個代數
&lt;/br&gt;

&lt;/section&gt;
&lt;section&gt;
&lt;h1&gt;心得&lt;/h1&gt;
以往用計算機的我們,現在我們可以利用python來製作簡易的函數計算,有了這個,運算大量代數的時就能用python語法做更高效能且準確的運算,比計算機的功能更進一步!
&lt;/section&gt;
&lt;section&gt;
    &lt;h1&gt;自評&lt;/h1&gt;
    &lt;p&gt;此課程寫的語法十分有趣,使我對這個課程印象深刻也更有興趣。給自己的分數:64分&lt;/p&gt;
&lt;/section&gt;
				
&lt;/div&gt;
&lt;/div&gt;
&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
&lt;/body&gt;

</t>
<t tx="leo.20151116214200.7">@language html
&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40423203-5&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;zero to hero python教學&lt;/h1&gt;
    &lt;p&gt;40423203 四設一乙 &lt;/p&gt;		
&lt;/section&gt;
	
&lt;section id="hw-task-five"&gt;
    &lt;h1&gt;作業四-任務說明&lt;/h1&gt;
    &lt;p&gt;10/23 作業: 完成 [02:20:00] Storing Numbers 課程研習(up to [03:14:26]), 必須在 10/30 上課前完成內容與自評&lt;/p&gt;   
&lt;/section&gt;
  
&lt;section&gt;
    &lt;h1&gt;有關"storing numbers"&lt;/h1&gt;
  sorting=存儲,number=數字
    影片指導我們使用python指令來做出一個簡易的函數方便我們帶入數字得到答案
    像收入,BMI,等等生活常用且簡易的加減乘除都可以用相關的指令做計算
&lt;/section&gt;
  
&lt;section&gt;
以面積舉例,如果要讓電腦知道"長","寬"是代表代數還是文字,我們只要打入:
.長=5,   
&lt;br /&gt;
.寬=20,   
&lt;br /&gt;
.面積=長*寬,   
&lt;br /&gt;
.print(面積),   
    &lt;br /&gt;
就會顯示出其面積
&lt;/section&gt;
				
&lt;section&gt;
.我們要讓答案顯示出文字,輸入
print("四方形的面積為"+面積),   
    &lt;br /&gt;
.然而出錯了,這是為何呢?   
&lt;/section&gt;
  
&lt;section&gt;
我們print裡面的字串不能同時存在文字(四方形的面積為)及代數(面積),所以我們要把代數轉換為文字,有幾個規則:   
    &lt;br /&gt;
.print("四方形的面積為%f" % 面積)&gt;&gt;四方形的面積為100.000000 ,   
    &lt;br /&gt;
.print("四方形的面積為%.2f" % 面積)&gt;&gt;四方形的面積為100.00 ,   
    &lt;br /&gt;
.print("四方形的面積為%d" % 100)&gt;&gt;四方形的面積為100,   
    &lt;br /&gt;
.print("四方形的面積為%3d "% 100)&gt;&gt;四方形的面積為(三個空格)100,   
    &lt;br /&gt;
.print("四方形的面積為%03f "%100)&gt;&gt;四方形的面積為100   
&lt;/section&gt;
  
&lt;section&gt;
1.%d不能用於代數,   
    &lt;br /&gt;
 .2.%f會讓答案默認為6個小數位,   
    &lt;br /&gt;
 .3.%.n會讓小數位變n位,   
    &lt;br /&gt;
 .4.%0n會用0把答案填到第n位,   
    &lt;br /&gt;
 .5.%n可以讓答案距離前面的文字n個空格
&lt;/section&gt;
  
&lt;section&gt;
還有另外一種表示方法,規則如下:   
print("四方形的面積為{0:d}".format(100))&gt;&gt;四方形的面積為100   
    .&lt;br /&gt;
 .print("四方形的面積{0:3d}".format(100))&gt;&gt;四方形的面積為   100   
    .&lt;br /&gt;
 print("四方形的面積為{0:f}".format(100))&gt;&gt;四方形的面積為100.000000   
    .&lt;br /&gt;
 "0:"後面的代碼與前面規則相同   
 .同樣地,d不能用在代數上   
&lt;/section&gt;
  
&lt;section&gt;
如果要讓答案顯示多個數字,我們可以:
 .print("四方形的長為{0:d},寬為{1:3d},面積 為{2:d}".format(5,20,100)),   
    &lt;br /&gt;
 可以得到:四方形的長為5,寬為20,面積為100
&lt;/section&gt;
  
&lt;section&gt;
也可以把這個代數弄成互動式的,運行之後輸入你要的數字,最後得到答案:   
    &lt;br /&gt;
 .長=input("長是多少"),   
    &lt;br /&gt;
 .寬=input("寬是多少"),   
     &lt;br /&gt;
 .周長=2*(長+寬),   
    &lt;br /&gt;
 .print(周長),   
    &lt;br /&gt;
 .但如果我們拿上面的5,20做示範我們得到的答案卻是1040  
&lt;/section&gt;
  
&lt;section&gt;
這個方法也不能讀取代數,所以我們可以在代數前面加個"format":   
 .周長=2*(長+寬)&gt;&gt;&gt;&gt;面積=format(長)*format(寬)   
    &lt;br /&gt;
 .終於,我們得到了50
&lt;/section&gt;
  
&lt;section&gt;
&lt;h1&gt;對Pythop課程的一些感想&lt;/h1&gt;
在簡單的算術上用這個軟體就像簡報用power point一樣笨重,但如果要進行大規模運算的話,輸入"規則"後只要改變代數就可以輕易運算出需要的答案,而且都是純文字檔,在檔案更新上比較不會有這麼多麻煩,又非常的輕便很棒
&lt;/section&gt;

&lt;section&gt;
&lt;h1&gt;上課內容的心得&lt;/h1&gt;
本週教的是Leo Editor的基本操作,又PyQt為Leo Editor的圖形介面,以及notebook.py須放在對應位置,plugin裡的liquid-tags用來將ipython notebook轉成pelican (轉檔)。
Leo Editor 基本操作:
"@edit:編輯檔案用 @path:指定路徑(標題指令) 
@button:執行指令 @clean:整體架構 @language:宣告內容 @others:所有從屬節點" 其中"@clean 和 @others" 掌握超元件。
&lt;/section&gt;
  
&lt;section&gt;
&lt;h1&gt;自評&lt;/h1&gt;
漸漸熟悉Leo Editor的操作,以緩慢的速度朝離我遙遠的進度邁進,仍然努力中,我想我總會追上的。給自己的分數是:66
&lt;/section&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
&lt;/body&gt;

</t>
<t tx="leo.20151116214200.8">@language html
&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40423203-6&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;zero to hero python教學&lt;/h1&gt;
    &lt;p&gt;40423203 四設一乙 &lt;/p&gt;		
&lt;/section&gt;
	
&lt;section id="hw-task-five"&gt;
 &lt;h1&gt;作業六-任務說明&lt;/h1&gt;
    &lt;p&gt;6.10/30 作業: 完成 [03:14:26] Working with Dates and Time(up to [04:05:53]) 課程研習, 必須在 11/6 上課前完成內容與自評&lt;/p&gt;   
&lt;/section&gt;
  
&lt;/section&gt;
    &lt;h1&gt;日期計算&lt;/h1&gt;
 python互動的進階模式,可以直接取電腦上的時間來進行計算
&lt;/section&gt;
  
&lt;section&gt;
我們先導入電腦時間,指令為:
&lt;br /&gt;
import dateline
&lt;br /&gt;
之後我們輸入現在時間,指令為:
&lt;br /&gt;
currentDate = datetime.date.today()
&lt;br /&gt;
最後還是用print來做輸出
&lt;br /&gt;
print(currentDate)
&lt;br /&gt;
就可以讓電腦用python認出電腦時間
&lt;/section&gt;
				
&lt;section&gt;
python也能認得年,月,:
    &lt;br /&gt;
print(currentDate.month)
&lt;br /&gt;
可以得到月
&lt;br /&gt;
print(currentDate.year)
&lt;br /&gt;
可以得到年
&lt;/section&gt;
&lt;section&gt;
&lt;h1&gt;使用strftime指令&lt;/h1&gt;
strftime可以把後續的代數指令變簡單一些,但非常難以記憶,通常是以書本或網路來記載:
    &lt;br /&gt;
 print(currentDate.strftime('%d %b, %Y'))
    &lt;br /&gt;
%d=日
    &lt;br /&gt;
%b=月
    &lt;br /&gt;
%Y=年
    &lt;br /&gt;
可以查詢'http://strftime.org/'來找更多關於strftime語法的使用
&lt;/section&gt;
  
&lt;section&gt;
&lt;h1&gt;對python課程的心得&lt;/h1&gt;
在python的語法下,兩種不同的語法亦有可能會產生一樣的結果,而部份情況下,strftime這個指令或許可以讓工作處理得更效率
&lt;/section&gt;

&lt;section&gt;
&lt;h1&gt;對上課的心得&lt;/h1&gt;
本週教的是各班協同作業,到Leo(組員節點)建立自己的節點,並將所有檔名改成自己的學號,解決衝突後,並推送至遠端倉儲。
&lt;/section&gt;
  
&lt;section&gt;
&lt;h1&gt;自評&lt;/h1&gt;
終於跟上老師的腳步了,開薰!!在經過這麼多禮拜首次跟上進度,但在最後推送至遠端時,因不熟悉上推流程,因此仍無法推送至遠端的全班偕同倉儲,感到十分可惜。回家後,與同學討論後,再次演練,並錄製影片,錄影當中遇到許多的問題,重複演練好幾遍,但也因為這樣多練習了好幾遍。給自己的分數是:67
&lt;/section&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
&lt;/body&gt;

</t>
<t tx="leo.20151116214200.9">@language html
&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40423203-7&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;zero to hero python教學&lt;/h1&gt;
    &lt;p&gt;40423203 四設一乙 &lt;/p&gt;		
&lt;/section&gt;
	
&lt;section id="hw-task-five"&gt;
    &lt;h1&gt;作業七&lt;/h1&gt;
    &lt;p&gt;&lt;/p&gt;   
&lt;/section&gt;
  
&lt;section&gt;
&lt;h1&gt;上課內容心得&lt;/h1&gt;
這個禮拜老師做了個總結,包括"用程式方法來管理資料,即利用線上教學來提升自我能力",還有:
程式基本概念 
print()
        整數;浮點數;字串;
        數列 (list) - [1, 2, 3] [1, 2, 3, [1, 2, [1, 2, 3] ] ] ;
        元組 (tuple) - (1, 2, 3)
        字典 (dictionary) - {"a": 1, "b": 2}
        重複迴圈 for
        邏輯判斷 if, while
        檔案輸出入 (file IO) 
        檔案與操作系統 (windows, Mac, Linux .....)
資料編碼
        函式 function 
        模組 (module)
        物件導向 (OOP)
        網際程式 javascript, html5, webgl
        資料庫 database, sql, nosql
&lt;/section&gt;
  
&lt;section&gt;
&lt;h1&gt;自評&lt;/h1&gt;
聽著老師對這些日子所學所做的總結,使我明白,網路的發展,使我們生活多采多姿,也帶給我們便利,不要只是用來玩樂,善加利用必能帶來不少利益。給自己的分數是:69
&lt;/section&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
&lt;/body&gt;

</t>
</tnodes>
</leo_file>
